complete -c rm -s f -d "Never prompt for removal"
complete -c rm -s i -d "Prompt for removal"
complete -c rm -s d -d "Remove directories as well"
complete -c rm -s P -d "Overwrite before removal"
complete -c rm -s R -s r -d "Recursively remove subdirs"
complete -c rm -s v -d "Explain what is done"
complete -c rm -s W -d "Undelete given filenames"
complete -c rm -s x -d "Don't traverse mount points"
complete -c rm -s I -d "Prompt to remove >=3 files"
