#!/bin/bash

while [ "$1" = "--" ]; do shift; done

editor=nvim

if [ -d "$1" ] && [ -d "$2" ]; then
    # Opening folders
    local=$1
    remote=$2

#     echo $local
#     echo $remote

    export EDITOR="$HOME/.local/bin/custom/codediff"
    # ranger $local
    $HOME/.local/bin/custom/explorer.js $remote
elif [ -f "$1" ] && [ -f "$2" ]; then
    # Opening folders
    local=`realpath $1`
    remote=`realpath $2`

    case "$editor" in
        "nvim")
            nvim -d $local $remote
            ;;
    esac
elif [ "`git rev-parse --show-toplevel`" ]; then
    # We are in a git directory
    if [ -d "$1" ]; then
        git difftool --dir-diff $1
    elif [ -f "$1" ]; then
        git difftool $1
    else
        if [ ! -f "$file" ]; then
            echo "Could not find '$1'"
            sleep 5
            exit 1
        fi
    fi
else
    # Opening a file
    file="$1"

    if [ ! -f "$file" ]; then
        echo "File '$file' not found!"
        sleep 5
        exit 1
    fi

    if [[ "$file" =~ /right/ ]]; then
        right=`realpath $file`
        left=`realpath ${file/right/left}`
    elif [[ "$file" =~ /left/ ]]; then
        left=`realpath $file`
        right=`realpath ${file/left/right}`
    else
        $editor "`realpath $file`"
        exit 0
    fi
    case "$editor" in
        "nvim")
            nvim -d $left $right
            ;;
    esac
fi
