#!/bin/bash


while [ $# -gt 0 ]; do
    if [ ! -e "$1" ]; then
        echo "File not found - '$1'"
        shift
        continue
    fi

    arg=$1
    arg=${arg%/}
    path=${arg%/*}
    file=${arg##*/}

    [ "$path" = "$file" ] && path='.'

    newfile=`sed -e 's/[^a-zA-Z0-9.]\+/_/g' -e 's/_\?\([^a-zA-Z0-9]\)_\?/\1/g' <<< "$file"`

    if [ "$newfile" = "$file" ]; then
        shift
        continue
    fi

    if [ -e "$path/$newfile" ]; then
        echo "File exists - '$path/$newfile'"
    else
        mv "$path/$file" "$path/$newfile"
    fi
    shift
done
