#!/bin/bash

cmd=$2
file=$1

if [ ! -f "$file" ]; then
    echo "USAGE = 'unlock <file> [cmd]'";
    echo
    echo -e "cmd will be ${BLUE}bat${NC} if not provided"
    exit 1;
fi

ft=`file "$file"`
ft="${ft#*: }"

if [[ ! "$ft" =~ "GPG symmetrically encrypted data" ]]; then
    echo "😿 '$file' does not seem to be GPG encrypted...";
    echo
    echo -e "Its type is '$BLUE${ft#*: }$NC'"
    exit 1;
fi

read -s -p '🔒 ' pass
echo

truename=${file%.*}
truename=${truename##*/}
if [ ! "$truename" ]; then
    truename=$RANDOM$RANDOM$RANDOM
fi

echo "$pass" | gpg -q --batch --yes --passphrase-fd 0 -o /tmp/$truename -d "$file" 2> /dev/null

if [ $? -ne 0 ]; then
    echo
    echo -e "${RED}❌ Wrong passphrase!${NC}"
    exit 1
fi

sum1=`md5sum /tmp/$truename | cut -d" " -f1`

if [ "$cmd" ]; then
    $cmd /tmp/$truename
else
    bat -pp /tmp/$truename
fi

sum2=`md5sum /tmp/$truename | cut -d" " -f1`

if [ "$sum1" != "$sum2" ]; then
    echo $sum1
    echo $sum2
    echo "You seem to have modified the file, do you want to overwrite the locked file?"

    res=''
    while [[ ! "$res" =~ [yn] ]]; do
        read -p "(y/n) > " res
    done

    if [ "$res" = "y" ]; then
        echo "$pass" | gpg --batch --yes --passphrase-fd 0 -o "$file" -c "/tmp/$truename"
    fi
fi

shred -u /tmp/$truename
